server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        # - id: insper
        #   uri: https://www.insper.edu.br
        #   predicates:
        #     - Path=/insper/**

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**
