name: store

services:
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-store}
      POSTGRES_USER: ${POSTGRES_DB:-store}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-store}
    ports:
      - 5432:5432